version: '3.8'

services:
  node-app:
    build: .
    depends_on:
      - postgresdb
    image: node-app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
