version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: postgresdb-util-dev
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user228
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    # driver: local
